#!/usr/bin/env python
# Potato Assembler Driver
# usage
#	./pad assembly.asm
#	to speficy memory size, either use the -p flag, or place the number in the .padconfig file
import sys
import assembler
import padformemory
from os.path import splitext
from os.path import dirname

def main():
	# check for size flag
	if sys.argv[1] == "-p":
		size = int(sys.argv[2])
		filestring = sys.argv[3]
	else:
		filestring = sys.argv[1]
		configfile = open(dirname(sys.argv[0]) + "/.padconfig", "r")
		configoptions = configfile.readlines()
		size = int(configoptions[0])

	# prepare file names for tools
	filenameparts = splitext(filestring)
	assemblyfile = filestring
	objectfile = filenameparts[0] + ".o"
	memoryfile = filenameparts[0] + ".mem"

	print "Assembling " + filenameparts[0] + filenameparts[1] + "",
	assembler.parse(assemblyfile, objectfile)
	print "done."
	print "Padding " + filenameparts[0] + ".o for memory of size " + str(size),
	padformemory.pad(objectfile, memoryfile, size)
	print "done."

if __name__ == '__main__':
	main()
